exports.platform_item_list = [
  'Domain',
  'MGR Technology',
  'Location',
  'Prime',
  'Activity',
  'Phase',
  'LAB ID',
  '# cells',
  '# Channel Emulator',
  '# UE',
  'RAN ID',
  'Controller Model',
  '# of Mobiles',
  '# of People',
  'Type of testing',
  'd2U type',
  'Modem',
  'RRH/TRDU band',
  '# of RRH/TRDU',
  'Destination',
  'Market',
  'Frequency Band',
  'Program',
  'Comments'
];